services:
  api:
    build: .
    image: talentai:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000

  streamlit:
    build: .
    image: talentai:latest
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - api
    command: >
      streamlit run main.py
      --server.port 8501
      --server.address 0.0.0.0

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
